#!/usr/bin/env python3
"""
Generates src/ui/frames.css: stretchable hand-torn UI frames as SVG data-URIs
(black fill + rough white outline in the style of the Dungeon Drivers UI kit).
"""
import random, urllib.parse, os

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src', 'ui', 'frames.css')


def torn_path(seed, amp=0.9, per_edge=7, corner=2.2, notches=3, inset=0.0, skew=0.0):
    r = random.Random(seed)
    L, T, R, B = 1 + inset, 1.5 + inset, 99 - inset, 98.5 - inset
    pts = []
    # corners nudged inward with slight skew (tl, tr, br, bl)
    tl = (L + r.uniform(0, corner) + skew, T + r.uniform(0, corner))
    tr = (R - r.uniform(0, corner) + skew, T + r.uniform(0, corner * 0.6))
    br = (R - r.uniform(0, corner) - skew, B - r.uniform(0, corner))
    bl = (L + r.uniform(0, corner) - skew, B - r.uniform(0, corner * 0.6))
    edges = [(tl, tr), (tr, br), (br, bl), (bl, tl)]
    for ei, (a, b) in enumerate(edges):
        pts.append(a)
        n = per_edge
        notch_at = set(r.sample(range(1, n), min(notches // 2 + (1 if ei % 2 == 0 else 0), n - 1)))
        for i in range(1, n):
            t = i / n + r.uniform(-0.03, 0.03)
            x = a[0] + (b[0] - a[0]) * t
            y = a[1] + (b[1] - a[1]) * t
            # perpendicular jitter
            dx, dy = b[0] - a[0], b[1] - a[1]
            ln = (dx * dx + dy * dy) ** 0.5 or 1
            nx, ny = -dy / ln, dx / ln
            j = r.uniform(-amp, amp)
            if i in notch_at:
                j = r.choice([-1, 1]) * r.uniform(1.6, 3.0)
            pts.append((x + nx * j, y + ny * j))
    return 'M' + ' L'.join(f'{x:.2f},{y:.2f}' for x, y in pts) + ' Z'


def svg(paths, w=100, h=100):
    s = f"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 {w} {h}' preserveAspectRatio='none'>{''.join(paths)}</svg>"
    return "url(\"data:image/svg+xml," + urllib.parse.quote(s, safe="/:=' ,;()") + "\")"


def panel(seed, stroke='#f4f1e8', fill='#09090c', sw=3, inner=None, amp=0.9):
    p = torn_path(seed, amp=amp)
    out = [f"<path d='{p}' fill='{fill}' stroke='{stroke}' stroke-width='{sw}' vector-effect='non-scaling-stroke' stroke-linejoin='miter'/>"]
    if inner:
        p2 = torn_path(seed + 1000, amp=0.5, inset=2.6, corner=1.2, notches=0)
        out.append(f"<path d='{p2}' fill='none' stroke='{inner}' stroke-width='1.2' vector-effect='non-scaling-stroke' opacity='.7'/>")
    return svg(out)


def slab(seed, fill, stroke=None, skew=4.0, amp=0.7):
    p = torn_path(seed, amp=amp, per_edge=6, corner=1.6, notches=4, skew=skew)
    st = f" stroke='{stroke}' stroke-width='2' vector-effect='non-scaling-stroke'" if stroke else ''
    return svg([f"<path d='{p}' fill='{fill}'{st}/>"])


RAR = {'r0': '#e9e6dc', 'r1': '#4dff6a', 'r2': '#3aa6ff', 'r3': '#c45cff', 'r4': '#ffb02b'}
vars_ = {}
for i, seed in enumerate([11, 23, 37, 51, 64]):
    vars_[f"jag-{'abcde'[i]}"] = panel(seed)
for k, col in RAR.items():
    vars_[f'jag-{k}'] = panel(70 + int(k[1]), stroke=col, inner=col)
vars_['jag-red'] = panel(91, stroke='#ff2a3c', inner='#f4f1e8')
vars_['jag-cyan'] = panel(92, stroke='#33d8ff', inner='#33d8ff')
vars_['jag-gold'] = panel(93, stroke='#ffcb2f', inner='#ffcb2f')
vars_['jag-grey'] = panel(94, stroke='#8b8f9c', inner='#5a5e6a')
vars_['jag-white'] = panel(95, stroke='#f4f1e8', fill='#f4f1e8', sw=2)
for i, seed in enumerate([101, 102, 103]):
    n = 'abc'[i]
    vars_[f'slab-red-{n}'] = slab(seed, '#ff2a3c')
    vars_[f'slab-blue-{n}'] = slab(seed + 10, '#1f7bff')
    vars_[f'slab-dark-{n}'] = slab(seed + 20, '#101014', '#f4f1e8')
    vars_[f'slab-gold-{n}'] = slab(seed + 30, '#ffcb2f')
css = ['/* generated by tools/gen_frames.py - do not edit */', ':root {']
for k, v in vars_.items():
    css.append(f'  --{k}-img: {v};')
css.append('}')
for k in vars_:
    css.append(f'.{k} {{ background: var(--{k}-img) 0 0 / 100% 100% no-repeat; }}')
open(OUT, 'w').write('\n'.join(css) + '\n')
print('wrote', OUT, os.path.getsize(OUT), 'bytes')
